name: Deploy Components to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@main
    with:
      bw-legacy: false
      deploy-env: "mainnet"
      app-name: "pokethe.near"
      deploy-account-address: pokethe.near
      signer-account-address: pokethe.near
      signer-public-key: ed25519:2GD4dd3DMVXDva9Tp2N8DmAatXyYDMdCJGzsJf3g3TCx
    secrets:
      SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}
